package com.tjohnn.routinechecks.data.local

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.util.*

@Entity(tableName = "routines")
data class RoutineEntity (
    /**
     * Autogenerated ID of routine
     */
    @PrimaryKey(autoGenerate = true)
    val id: Int,

    /**
     * Routine title
     */
    val title: String,

    /**
     * Routine description
     */
    val description: String,

    /**
     * Next time that this routine is taking place
     */
    val nextCheckTime: Long,

    /**
     * Number of times this routine has been missed
     */
    val numberOfMissed: Int,

    /**
     * Number of times this routine has been marked as done
     */
    val numberOfDone: Int,

    /**
     * Interval of time(in [durationUnit]) this routine has to be carried out
     */
    val routineFrequency: Int,

    /**
     * Duration unit by which [routineFrequency] is being measured
     */
    val durationUnit: String,

    /**
     * Specifies if the this routine has a pending elapsed time
     */
    val isPending: Boolean,

    /**
     * The previous check time of this routine. This is needed for some computation
     */
    val previousCheckTime: Long
)